"""Structured memory for the NOVA take-over (baseline as of 30 Sep 2026, 09:00 Montréal).

Every fact cites at least one source. A source is a dict:
  file    path relative to the corpus folder (Projet360_NOVA_ETUDIANTS)
  anchor  text that must appear in that file (checked by tests/test_nova.py)
  kind    eml | txt | md | pdf | xlsx | png | csv

Kinds of fact, kept separate on purpose:
  proposition  someone suggests something; not a decision
  decision     an authority decided (committee, decision note, ADR)
  validation   an accountable person accepted the result
  livraison    a supplier or team says it delivered; not accepted
  statut       a status shown in a report or register
  information  a plain fact (dates, amounts, scope)
"""

from __future__ import annotations

ROOT = "loto-quebec-nova-participants/Projet360_NOVA_ETUDIANTS"  # relative to the polyai folder
BASELINE = "2026-09-30T09:00:00-04:00"


def S(file: str, anchor: str, kind: str | None = None, note: str = "") -> dict:
    if kind is None:
        kind = file.rsplit(".", 1)[-1]
    return {"file": file, "anchor": anchor, "kind": kind, "note": note}


# ---------------------------------------------------------------------------
# Chronology. Each item: id, date (ISO), time, kind, summary, sources, status
# ---------------------------------------------------------------------------
FACTS = [
    dict(id="F01", date="2026-07-07", time="", kind="information",
         summary="Démarrage de NOVA confirmé. Budget initial 180 000 $ CAD, mise en production ciblée au 15 octobre, Élodie Caron chargée de projet.",
         sources=[S("01_Courriels/E01_Lancement_NOVA.eml", "Je confirme le démarrage de NOVA"),
                  S("02_Reunions/M01_CR_Demarrage_07juillet.txt", "Élodie Caron agit comme chargée de projet"),
                  S("04_Documents_projet/Charte_Projet_NOVA_v1.txt", "Date cible de mise en production : 15 octobre 2026")],
         status="date remplacée par F19"),
    dict(id="F02", date="2026-07-18", time="", kind="information",
         summary="Architecture v1 préparée, hébergement East US (landing zone standard de Boréal).",
         sources=[S("06_Architecture_et_decisions/Architecture_NOVA_v1.pdf", "Version initiale préparée avant la décision de localisation")],
         status="remplacée par ADR-007 (F05)"),
    dict(id="F03", date="2026-07-22", time="14:32", kind="proposition",
         summary="Sophie Lambert demande si East US est compatible; elle veut que les données de production restent au Canada.",
         sources=[S("01_Courriels/E02_Question_hebergement.eml", "je veux que les données de production demeurent au Canada")],
         status="ouvert jusqu'à F04"),
    dict(id="F04", date="2026-07-23", time="09:10-09:12", kind="decision",
         summary="Atelier architecture : Canada Central retenu. Élodie note la décision, Marc Gervais et Sophie Lambert disent oui, Julien Moreau (Boréal) confirme. SSO seulement en production.",
         sources=[S("02_Reunions/M02_Transcript_Architecture_23juillet.txt", "Donc on tranche Canada Central"),
                  S("02_Reunions/M02_Transcript_Architecture_23juillet.txt", "Canada Central, SSO uniquement")],
         status="en vigueur"),
    dict(id="F05", date="2026-07-23", time="", kind="decision",
         summary="ADR-007 acceptée : production de NOVA dans Canada Central. Conséquence : migration des ressources, mise à jour du schéma, et validation technique avant les tests de production.",
         sources=[S("06_Architecture_et_decisions/ADR-007_Localisation_donnees.md", "L'environnement de production de NOVA sera déployé dans **Canada Central**"),
                  S("06_Architecture_et_decisions/ADR-007_Localisation_donnees.md", "Une validation technique doit confirmer la migration avant les tests de production")],
         status="acceptée"),
    dict(id="F06", date="2026-07-31", time="", kind="information",
         summary="Facture INV-001 : acompte développement phase 1, 60 000 $, statut payée.",
         sources=[S("05_Contrats_et_finances/INV-001.pdf", "Développement phase 1 - acompte")],
         status="payée"),
    dict(id="F07", date="2026-08-14", time="", kind="decision",
         summary="CR-01 (rapports avancés et export de synthèse) approuvée par le comité de projet : 24 000 $, aucun changement de date cible.",
         sources=[S("05_Contrats_et_finances/CR-01_Rapports_avances_APPROUVE.pdf", "APPROUVÉE"),
                  S("05_Contrats_et_finances/CR-01_Rapports_avances_APPROUVE.pdf", "Aucun changement de la date cible")],
         status="approuvée"),
    dict(id="F08", date="2026-08-15", time="", kind="validation",
         summary="ACC-301 (labels du champ nom) fermé : validé avec NVDA et VoiceOver par Mélissa Gagnon.",
         sources=[S("03_Tickets/ACC-301.txt", "15 août - Mélissa : Validé avec NVDA et VoiceOver. Fermé.")],
         status="fermé"),
    dict(id="F09", date="2026-08-20", time="", kind="validation",
         summary="ACC-302 (contraste) fermé : re-test à 5,3:1 par Mélissa Gagnon. Même jour, Julien Moreau écrit que « tout devrait être conforme » côté accessibilité (courriel E04).",
         sources=[S("03_Tickets/ACC-302.txt", "20 août - Mélissa : Re-test OK à 5,3:1. Fermé."),
                  S("01_Courriels/E04_Corrections_accessibilite.eml", "Tout devrait maintenant être conforme de notre côté")],
         status="fermé"),
    dict(id="F10", date="2026-08-25", time="", kind="livraison",
         summary="Architecture v2 : production en Canada Central, « version révisée après ADR-007 ».",
         sources=[S("06_Architecture_et_decisions/Architecture_NOVA_v2.pdf", "Version révisée après ADR-007")],
         status="version courante du schéma"),
    dict(id="F11", date="2026-08-26", time="09:05", kind="livraison",
         summary="Boréal (Julien Moreau) annonce que la migration vers Canada Central est complétée, avec un test de déploiement et de connectivité sans blocage. Le schéma v2 est joint.",
         sources=[S("01_Courriels/E03_Confirmation_Canada_Central.eml", "La migration des ressources prévues pour NOVA vers Canada Central est complétée")],
         status="déclarée par le fournisseur"),
    dict(id="F12", date="2026-08-27", time="", kind="statut",
         summary="Comité du 27 août : migration déclarée terminée par Boréal et vérifiée par l'équipe architecture. Accessibilité : plusieurs anomalies, certaines corrigées, d'autres en traitement. Doublons du premier lot à investiguer. Sophie demande que la journalisation admin soit vérifiée en situation réelle.",
         sources=[S("02_Reunions/M03_CR_Comite_27aout.txt", "La migration de l'architecture vers Canada Central est déclarée terminée")],
         status="compte rendu"),
    dict(id="F13", date="2026-08-31", time="", kind="information",
         summary="Facture INV-002 : jalon 2 (48 000 $) et CR-01 (24 000 $), total 72 000 $, payée.",
         sources=[S("05_Contrats_et_finances/INV-002.pdf", "Rapports avancés - CR-01")],
         status="payée"),
    dict(id="F14", date="2026-09-02", time="", kind="information",
         summary="DATA-401 ouvert : doublons de dossiers dans le lot de migration MIG-09-02 (même demandeur, même courriel, timestamps espacés d'une seconde).",
         sources=[S("03_Tickets/DATA-401.txt", "Le même dossier peut être créé deux fois"),
                  S("03_Tickets/DATA-401_echantillon.csv", "REQ-4451")],
         status="fermé le 9 sept (F18)"),
    dict(id="F15", date="2026-09-05", time="11:18", kind="information",
         summary="INT-101 : le connecteur interne renvoie des 401. Boréal attribue cela au jeton de service expiré après le changement de secret.",
         sources=[S("03_Tickets/INT-101.txt", "Le jeton de service semble expiré après le changement de secret"),
                  S("03_Tickets/INT-101_extrait_logs.txt", "refresh_attempt=false")],
         status="cause initiale"),
    dict(id="F16", date="2026-09-08", time="08 sept 16:02", kind="information",
         summary="Marc Gervais : remplacement du secret fait mais erreurs intermittentes; il juge que le 15 octobre est en risque sans stabilité cette semaine.",
         sources=[S("03_Tickets/INT-101.txt", "Ça met en risque le 15 octobre")],
         status="ouvert jusqu'à F25 (fermeture INT-101)"),
    dict(id="F17", date="2026-09-08", time="11:16", kind="proposition",
         summary="Julien Moreau (Boréal) recommande de déplacer la mise en production du 15 au 22 octobre. Il précise : « il s'agit d'une proposition de notre part. À vous de confirmer la décision de gouvernance. »",
         sources=[S("01_Courriels/E05_Retard_integration.eml", "Notre recommandation est de déplacer la mise en production au **22 octobre**"),
                  S("01_Courriels/E05_Retard_integration.eml", "il s'agit d'une proposition de notre part")],
         status="proposition"),
    dict(id="F18", date="2026-09-09", time="", kind="validation",
         summary="DATA-401 validé : un lot de 15 000 événements rejoué sans doublon. Ticket fermé.",
         sources=[S("03_Tickets/DATA-401.txt", "aucun doublon détecté")],
         status="fermé"),
    dict(id="F19", date="2026-09-10", time="15:22-15:25", kind="decision",
         summary="Comité de direction : Élodie Caron formule la décision de déplacer la date au 22 octobre 2026 et la déclare approuvée. Sophie, Marc et Olivier répondent « Non » à l'objection; Nicolas dit « D'accord ». Aucune pénalité contractuelle identifiée (15:18).",
         sources=[S("02_Reunions/M04_Transcript_Comite_direction_10sept.txt", "Donc **approuvé**. Le 22 devient la date officielle."),
                  S("02_Reunions/M04_Transcript_Comite_direction_10sept.txt", "Pas de pénalité identifiée")],
         status="approuvée; conditionnelle (F36)"),
    dict(id="F20", date="2026-09-10", time="15:35-15:40", kind="decision",
         summary="Comité du 10 septembre : mobile avancé (estimation Boréal d'environ 18 000 $) traité séparément. Aucune approbation de dépense.",
         sources=[S("02_Reunions/M04_Transcript_Comite_direction_10sept.txt", "aucune approbation aujourd'hui"),
                  S("02_Reunions/M04_Transcript_Comite_direction_10sept.txt", "Mobile : aucune décision de dépense")],
         status="aucune décision de dépense"),
    dict(id="F21", date="2026-09-12", time="", kind="statut",
         summary="Plan projet v3 : P-06 (mise en production) assigné à Nicolas Perron, mais la date reste le 15 octobre (« cible de planification »). Le plan n'a pas été corrigé pour le 22 octobre.",
         sources=[S("04_Documents_projet/Plan_Projet_NOVA_v3_12sept.xlsx", "Cible de planification", kind="xlsx", note="Plan projet!D7 et G7 ; E7:F7 = 2026-10-15")],
         status="obsolète sur la date"),
    dict(id="F22", date="2026-09-12", time="", kind="information",
         summary="SEC-210 ouvert (priorité bloquante avant production) : l'événement EXPORT_CSV du journal d'audit n'a ni objet ni résultat.",
         sources=[S("03_Tickets/SEC-210.txt", "Priorité : Bloquante avant production"),
                  S("03_Tickets/SEC-210_audit.png", "", kind="png", note="capture : ligne EXPORT_CSV, objet et résultat à « --- »")],
         status="en validation (F28, F38)"),
    dict(id="F23", date="2026-09-15", time="09:18", kind="information",
         summary="Teams : Nicolas rappelle que le comité a approuvé le 22 octobre le 10 septembre et que le plan n'a pas été corrigé.",
         sources=[S("07_Conversations_Teams/Teams_15sept_ProjetNOVA.txt", "le comité a approuvé le 22 octobre le 10 septembre")],
         status="confirme F19"),
    dict(id="F24", date="2026-09-16", time="08:35", kind="decision",
         summary="Transfert de la charge de projet : Nicolas Perron prend officiellement NOVA à compter du 16 septembre. Élodie Caron reste joignable quelques jours.",
         sources=[S("01_Courriels/E06_Transition_charge_projet.eml", "Nicolas Perron prend officiellement la charge du projet NOVA"),
                  S("07_Conversations_Teams/Teams_16sept_Transition.txt", "Nicolas reprend officiellement NOVA"),
                  S("04_Documents_projet/Note_transition_Elodie_16sept.txt", "Nicolas Perron reprend le rôle de chargé de projet NOVA")],
         status="en vigueur"),
    dict(id="F25", date="2026-09-17", time="14:23-16:10", kind="validation",
         summary="INT-101 fermé : correctif déployé (rotation du secret et correction du renouvellement du jeton), 120 recherches rejouées avec 120 réponses valides. Validé côté intégration par Marc Gervais.",
         sources=[S("03_Tickets/INT-101.txt", "Résolution : rotation du secret"),
                  S("01_Courriels/E12_Resolution_integration.eml", "120/120 recherches ont retourné les résultats attendus"),
                  S("03_Tickets/INT-101_extrait_logs.txt", "200 OK 187ms")],
         status="fermé (en intégration; production non démontrée)"),
    dict(id="F26", date="2026-09-17", time="13:14", kind="information",
         summary="ACC-303 ouvert (priorité haute) : la popup de modification ne permet pas d'atteindre le bouton Enregistrer au clavier. Reproduit par Boréal le 18 septembre.",
         sources=[S("03_Tickets/ACC-303.txt", "le bouton Enregistrer n'est jamais atteint avec Tab"),
                  S("03_Tickets/ACC-303_focus.png", "", kind="png", note="capture : « Le focus clavier ne rejoint pas ce bouton »")],
         status="ouvert (F37)"),
    dict(id="F27", date="2026-09-18", time="", kind="statut",
         summary="Suivi livraison : INT-101 fermé; DATA-401 validé; PERF-501 sous la cible d'une seconde; ACC-301 et ACC-302 fermés; navigation clavier sur modale à vérifier; runbook pas final. « Le 22 octobre reste la date approuvée » et les critères de go-live restent.",
         sources=[S("02_Reunions/M05_CR_Suivi_18sept.txt", "Le 22 octobre reste la date approuvée")],
         status="compte rendu"),
    dict(id="F28", date="2026-09-19", time="10:22", kind="livraison",
         summary="SEC-210 : Boréal annonce un correctif déployé en validation (« pour nous c'est réglé »). Sophie Lambert répond qu'il faut refaire leur propre scénario et ne pas fermer avant la validation sécurité.",
         sources=[S("03_Tickets/SEC-210.txt", "Fix déployé sur l'environnement de validation"),
                  S("03_Tickets/SEC-210.txt", "Ne pas fermer avant validation sécurité"),
                  S("07_Conversations_Teams/Teams_19sept_Securite.txt", "« déployé » != « accepté »"),
                  S("01_Courriels/E08_Correctif_journalisation.eml", "pour nous, le problème est corrigé")],
         status="livré, non accepté"),
    dict(id="F29", date="2026-09-21", time="", kind="statut",
         summary="Rapport de statut du 21 septembre : Échéancier VERT (cible 22 octobre), Budget VERT, Sécurité VERT (« correctif SEC-210 livré »), Accessibilité VERT (« correctifs appliqués »), Exploitation JAUNE. Le rapport note qu'il a été préparé avant la dernière vérification détaillée de certains tickets.",
         sources=[S("04_Documents_projet/Rapport_Statut_21sept.pdf", "Correctif SEC-210 livré"),
                  S("04_Documents_projet/Rapport_Statut_21sept.pdf", "préparé avant la dernière vérification détaillée")],
         status="contredit par les tickets (X03)"),
    dict(id="F30", date="2026-09-21", time="16:28", kind="statut",
         summary="Brouillon de communication d'Alex Deschamps : « NOVA est au vert. La sécurité et l'accessibilité sont complétées », fondé sur le rapport de statut. Non validé par Nicolas dans le corpus.",
         sources=[S("01_Courriels/E11_Communication_statut.eml", "NOVA est au vert")],
         status="brouillon; contredit (X04)"),
    dict(id="F31", date="2026-09-22", time="13:03", kind="proposition",
         summary="Julien Moreau pense que le mobile avancé était inclus dans le périmètre initial. Nicolas répond : compatibilité de base oui, optimisation CR-04 à 18 k$ non, non approuvée.",
         sources=[S("07_Conversations_Teams/Teams_22sept_Mobile.txt", "Le package d'optimisation CR-04 à 18k non")],
         status="contredit par F34"),
    dict(id="F32", date="2026-09-22", time="", kind="livraison",
         summary="Facture INV-003 datée du 22 septembre, statut « En validation » : jalon 3 (36 000 $) et « Optimisation interface mobile - CR-04 » (18 000 $), total 54 000 $.",
         sources=[S("05_Contrats_et_finances/INV-003.pdf", "Optimisation interface mobile - CR-04"),
                  S("05_Contrats_et_finances/INV-003.pdf", "En validation")],
         status="en validation"),
    dict(id="F33", date="2026-09-23", time="10:18", kind="proposition",
         summary="Amélie Fortin (Finances) valide INV-003 mais demande l'approbation correspondant à la ligne CR-04 de 18 000 $. Elle ne trouve qu'un brouillon.",
         sources=[S("01_Courriels/E07_Facture_003_question.eml", "Peux-tu me transmettre l'approbation correspondante")],
         status="question ouverte"),
    dict(id="F34", date="2026-09-24", time="13:42", kind="decision",
         summary="Décision de portée : les optimisations mobiles avancées (CR-04) sont reportées à la phase 2. Aucune dépense liée à CR-04 sans nouvelle approbation.",
         sources=[S("06_Architecture_et_decisions/Decision_Portee_Phase2.md", "reportées à la phase 2"),
                  S("01_Courriels/E10_Fonction_mobile.eml", "Aucune dépense liée à CR-04 ne doit être engagée ou facturée")],
         status="en vigueur"),
    dict(id="F35", date="2026-09-25", time="", kind="statut",
         summary="OPS-601 ouvert : runbook pas prêt. La capture (version du 25 septembre) montre les étapes 1 à 3 OK, l'étape 4 « Procédure de retour arrière » à TODO et l'étape 5 « Validation fonctionnelle post-déploiement » à compléter.",
         sources=[S("03_Tickets/OPS-601.txt", "Il manque au minimum la procédure de rollback"),
                  S("03_Tickets/OPS-601_runbook.png", "", kind="png", note="capture : étape 4 TODO, étape 5 « À compléter »")],
         status="ouvert (F41)"),
    dict(id="F36", date="2026-09-26", time="10:00-10:34", kind="decision",
         summary="Comité du 26 septembre : trois conditions concrètes pour le 22 octobre : (1) validation sécurité de SEC-210, (2) fermeture de ACC-303, (3) approbation du runbook incluant le rollback. Nicolas demande que ce soit écrit : la cible est conditionnelle. Sophie, Mélissa et Olivier confirment.",
         sources=[S("02_Reunions/M06_Transcript_Comite_26sept.txt", "trois conditions concrètes"),
                  S("02_Reunions/M06_Transcript_Comite_26sept.txt", "c'est conditionnel à ces trois éléments")],
         status="en vigueur"),
    dict(id="F37", date="2026-09-26", time="11:03", kind="statut",
         summary="ACC-303 toujours ouvert : Mélissa Gagnon note qu'un correctif est annoncé pour la prochaine build.",
         sources=[S("03_Tickets/ACC-303.txt", "Toujours ouvert. Correctif annoncé pour la prochaine build.")],
         status="ouvert"),
    dict(id="F38", date="2026-09-26", time="15:40", kind="statut",
         summary="SEC-210 : re-test planifié par Sophie Lambert. Le statut reste EN VALIDATION.",
         sources=[S("03_Tickets/SEC-210.txt", "Re-test planifié. Statut maintenu EN VALIDATION.")],
         status="en validation"),
    dict(id="F39", date="2026-09-27", time="17:02", kind="proposition",
         summary="Rappel de Nicolas Perron : la cible approuvée reste le 22 octobre, conditionnelle aux validations sécurité, accessibilité et préparation exploitation. Ne pas communiquer le 22 comme un go garanti.",
         sources=[S("01_Courriels/E09_Rappel_mise_en_production.eml", "la cible approuvée demeure le 22 octobre")],
         status="en vigueur"),
    dict(id="F40", date="2026-09-29", time="", kind="statut",
         summary="Registre des risques : R-01 retard du connecteur « Ouvert », suivi au 9 septembre (obsolète). R-02 sécurité, R-03 exploitation et R-04 accessibilité ouverts. R-05 migration données fermé.",
         sources=[S("04_Documents_projet/Registre_Risques_29sept.xlsx", "Ouvert", kind="xlsx", note="Risques!F2 = Ouvert, H2 = Suivi au 9 septembre 2026"),
                  S("04_Documents_projet/Registre_Risques_29sept.xlsx", "Fermé", kind="xlsx", note="Risques!F6 = Fermé")],
         status="R-01 obsolète"),
    dict(id="F41", date="2026-09-29", time="", kind="statut",
         summary="OPS-601 : version finale du runbook toujours non reçue par Olivier Côté.",
         sources=[S("03_Tickets/OPS-601.txt", "Toujours pas reçu la version finale")],
         status="ouvert"),
]

# Contract and fixed reference points (not dated events)
REFERENCE = [
    dict(id="R01", kind="information",
         summary="Contrat : montant maximal initial 180 000 $ CAD (hors taxes), période du 7 juillet au 31 octobre 2026. Tout travail hors portée exige une demande de changement écrite et approuvée avant exécution et facturation.",
         sources=[S("05_Contrats_et_finances/CONTRAT_Boreal_NOVA.pdf", "Montant maximal initial"),
                  S("05_Contrats_et_finances/CONTRAT_Boreal_NOVA.pdf", "Tout travail hors portée")]),
    dict(id="R02", kind="information",
         summary="Portée de la phase 1 : SSO, création et suivi de demandes, pièces jointes, workflow, tableau de suivi, rapports standards.",
         sources=[S("04_Documents_projet/Charte_Projet_NOVA_v1.txt", "Portée phase 1"),
                  S("02_Reunions/M01_CR_Demarrage_07juillet.txt", "La phase 1 comprend")]),
    dict(id="R03", kind="information",
         summary="Plan projet v2 : P-06 mise en production assigné à Élodie Caron, 15 octobre, note « Cible initiale ».",
         sources=[S("04_Documents_projet/Plan_Projet_NOVA_v2.xlsx", "Cible initiale", kind="xlsx", note="Plan projet!D7 = Élodie Caron, G7 = Cible initiale")]),
    dict(id="R04", kind="information",
         summary="Plan préliminaire de juin : mise en production au 15 octobre, « Version préliminaire ». Document ancien, à ne pas utiliser pour la date.",
         sources=[S("08_Archives_et_documents_connexes/Plan_NOVA_preliminaire_juin.xlsx", "Version préliminaire", kind="xlsx", note="Plan projet!G3")]),
    dict(id="R05", kind="information",
         summary="CR-04 (optimisation mobile) : brouillon, 18 000 $ estimés, demande du 4 septembre, aucun numéro d'approbation ni signature de comité.",
         sources=[S("05_Contrats_et_finances/CR-04_Optimisation_mobile_BROUILLON.pdf", "Aucun numéro d'approbation ni signature")]),
    dict(id="R06", kind="information",
         summary="INV-778 concerne le projet ORION (41 000 $), pas NOVA. Exclue de tous les calculs.",
         sources=[S("08_Archives_et_documents_connexes/INV-778_Projet_ORION.pdf", "Cette facture concerne un autre projet")]),
]

# Contradictions, and how each one is resolved
CONTRADICTIONS = [
    dict(id="X01", topic="Date de mise en production",
         claims="Charte v1 (7 juillet), plan v2 (« cible initiale »), plan v3 (12 septembre) et plan préliminaire de juin : 15 octobre.",
         resolution="Le comité du 10 septembre a approuvé le 22 octobre (F19). Autorité : décision de comité, prévaut sur la charte, qui dit elle-même ne pas être mise à jour automatiquement. Les plans sont en retard : à corriger.",
         sources=["F19", "R03", "F21", "R04"]),
    dict(id="X02", topic="Responsable de P-06 avant le transfert",
         claims="Plan v3 daté du 12 septembre attribue P-06 à Nicolas Perron, quatre jours avant son transfert officiel.",
         resolution="Le transfert est effectif le 16 septembre (F24). La date de la version du plan ne correspond pas au rôle : information incertaine, pas de changement de décision.",
         sources=["F21", "F24"]),
    dict(id="X03", topic="Statut du rapport de statut du 21 septembre",
         claims="Sécurité VERT (« correctif livré ») et Accessibilité VERT (« correctifs appliqués »).",
         resolution="SEC-210 est en validation et n'est pas accepté (F28, F38). ACC-303 est ouvert (F26, F37). Le rapport se déclare lui-même préparé avant la vérification des tickets. Les tickets, plus récents et plus précis, prévalent.",
         sources=["F29", "F28", "F26", "F37"]),
    dict(id="X04", topic="Message de statut « NOVA est au vert »",
         claims="Brouillon d'Alex Deschamps : sécurité et accessibilité complétées, cible 22 octobre.",
         resolution="Contredit par X03. Nicolas Perron a demandé le 27 septembre de ne pas présenter le 22 comme un go garanti (F39). Le brouillon ne doit pas être diffusé tel quel.",
         sources=["F30", "F39"]),
    dict(id="X05", topic="Accessibilité « tout conforme » (20 août)",
         claims="Julien Moreau : « tout devrait maintenant être conforme de notre côté » (E04).",
         resolution="Antérieur à l'apparition de ACC-303 (17 septembre) et au deuxième passage clavier sur modales demandé le 27 août (M03) et rappelé le 18 septembre (M05). Non retenu : l'accessibilité n'est pas complétée.",
         sources=["F09", "F12", "F26", "F27"]),
    dict(id="X06", topic="Mobile avancé dans le périmètre",
         claims="Julien Moreau (22 septembre) : le mobile était « inclus dans le scope initial ».",
         resolution="Périmètre phase 1 (R02) sans optimisation mobile avancée; décision de portée du 24 septembre (F34) et comité du 10 septembre (F20). Autorité de décision : prévaut. Pas d'approbation de CR-04.",
         sources=["F31", "R02", "F34", "F20"]),
    dict(id="X07", topic="SEC-210 : « réglé » contre « accepté »",
         claims="Boréal : correctif déployé, « pour nous c'est réglé » (19 septembre).",
         resolution="Sophie Lambert : « déployé » n'est pas « accepté ». Validation sécurité requise et re-test planifié (F28, F38). Non acceptée.",
         sources=["F28", "F38"]),
    dict(id="X08", topic="Ligne CR-04 dans la facture INV-003",
         claims="INV-003 facture 18 000 $ pour l'optimisation mobile CR-04, en validation.",
         resolution="CR-04 est un brouillon non approuvé (R05), exclue de la phase 1 (F34) : aucune dépense sans approbation. Cette ligne doit être retenue, voir action A05.",
         sources=["F32", "R05", "F34", "F33"]),
    dict(id="X09", topic="Localisation des données et migration",
         claims="Architecture v1 : East US (18 juillet). Courriel E03 du 26 août : migration Canada Central complétée, sans blocage.",
         resolution="ADR-007 (23 juillet) remplace v1 sur ce point. La migration est déclarée et vérifiée (F12). Mais l'ADR exige une validation technique distincte avant les tests de production : aucun document de cette validation dans le corpus. Le courriel E03 et sa PJ v2 ne sont pas deux confirmations indépendantes.",
         sources=["F02", "F05", "F11", "F10", "F12"]),
    dict(id="X10", topic="Risque connecteur R-01",
         claims="Registre du 29 septembre : R-01 « Ouvert », suivi au 9 septembre.",
         resolution="INT-101 fermé le 17 septembre (F25), confirmé par M05 (18 septembre) et le courriel E12. Le registre est obsolète. Il faut le mettre à jour, sans effacer l'historique.",
         sources=["F40", "F25", "F27"]),
    dict(id="X11", topic="Compte rendu du comité du 26 septembre",
         claims="Nicolas Perron : « Je publie le compte rendu ». Le corpus ne contient qu'une transcription partielle (10:00-10:34).",
         resolution="Le compte rendu signé n'est pas dans le corpus. La transcription suffit pour les trois conditions, mais leur formulation officielle doit être vérifiée.",
         sources=["F36"]),
    dict(id="X12", topic="Approbation formelle du 22 octobre",
         claims="Élodie Caron déclare « approuvé » (F19). Julien « Compris », Mélissa et Camille ne répondent pas explicitement.",
         resolution="Le compte rendu écrit du comité du 10 septembre n'est pas dans le corpus. La décision est confirmée par la transcription, par le Teams du 15 septembre, par M05 et par E09. Retenue comme décision, avec la réserve d'un compte rendu signé à obtenir.",
         sources=["F19", "F23", "F27", "F39"]),
]

# Sources that look relevant but must not be counted as independent evidence or as facts
SOURCE_NOTES = [
    ("Courriel_archive_17sept.eml", "Copie du courriel E12 (INT-101 fermé). Pas une confirmation indépendante."),
    ("E02, E03, E07, E10, E11 : pièces jointes", "Identiques (SHA-256) aux fichiers séparés. Une seule source, comptée une fois."),
    ("Notes_personnelles_quelquun.txt", "Notes non officielles, auteur non identifié (« 15 oct encore date? probablement »). Ignorées pour les faits."),
    ("Newsletter_Boreal_Septembre.txt, Invitation_Formation_Excel.txt", "Hors sujet."),
    ("Image-defi-2.png (racine)", "Affiche marketing de la solution. Aucun fait du projet."),
    ("Plan_NOVA_preliminaire_juin.xlsx", "Ancien. Utilisé seulement pour expliquer l'origine de la date du 15 octobre."),
]

# Budget (CAD, hors taxes). Every number is traced to a source.
BUDGET = dict(
    contract_initial=180_000,
    cr_approved=24_000,  # CR-01, F07
    cr_draft=18_000,  # CR-04, R05 (not approved, excluded)
    invoices=[
        dict(id="INV-001", amount=60_000, status="Payée", date="2026-07-31", note="acompte phase 1", ref="F06"),
        dict(id="INV-002", amount=72_000, status="Payée", date="2026-08-31", note="jalon 2 48 000 + CR-01 24 000", ref="F13"),
        dict(id="INV-003", amount=54_000, status="En validation", date="2026-09-22", note="jalon 3 36 000 + CR-04 18 000 (non approuvé)", ref="F32"),
    ],
    excluded=[dict(id="INV-778", amount=41_000, note="projet ORION", ref="R06")],
)


def budget_summary() -> dict:
    authorized = BUDGET["contract_initial"] + BUDGET["cr_approved"]
    invoiced = sum(i["amount"] for i in BUDGET["invoices"])
    paid = sum(i["amount"] for i in BUDGET["invoices"] if i["status"] == "Payée")
    pending = invoiced - paid
    cr04 = BUDGET["cr_draft"]
    billable_ok = invoiced - cr04
    return dict(
        authorized=authorized,
        invoiced=invoiced,
        paid=paid,
        pending=pending,
        cr04_to_hold=cr04,
        pending_ok=pending - cr04,
        billable_ok=billable_ok,
        unbilled_authorized=authorized - billable_ok,
    )


# Actions. owner = "proposé" (our suggestion) or "confirmé" (named in the corpus).
ACTIONS = [
    dict(id="A01", priority=1, action="Re-tester SEC-210 (journal d'audit : EXPORT_CSV avec objet et résultat) et donner ou refuser l'acceptation sécurité.",
         owner="Sophie Lambert", owner_status="confirmé (demandeuse et re-test, F38)",
         evidence="SEC-210.txt (commentaire du 26 sept); SEC-210_audit.png", due="à confirmer (re-test planifié, date non indiquée)",
         condition="Condition 1 (F36)", theme="Sécurité"),
    dict(id="A02", priority=1, action="Livrer le correctif de la popup ACC-303 (focus vers Enregistrer) et refaire le passage clavier sur les modales.",
         owner="Boréal (Julien Moreau), validation par Mélissa Gagnon", owner_status="confirmé (F37, M06)",
         evidence="ACC-303.txt (26 sept); ACC-303_focus.png; M06 10:12", due="à confirmer (« prochaine build »)",
         condition="Condition 2 (F36)", theme="Accessibilité"),
    dict(id="A03", priority=1, action="Finaliser le runbook : procédure de retour arrière (étape 4) et validation fonctionnelle post-déploiement (étape 5), exécutable par une personne extérieure à l'équipe projet, puis approbation.",
         owner="Olivier Côté (approbation); Boréal ops (rédaction du rollback)", owner_status="confirmé (OPS-601, M06 10:07-10:12)",
         evidence="OPS-601.txt (25 et 29 sept); OPS-601_runbook.png (version 25 sept)", due="à confirmer (« quelques jours avant » le go, M04 15:12)",
         condition="Condition 3 (F36)", theme="Exploitation"),
    dict(id="A04", priority=2, action="Mettre à jour le plan projet (P-06 et les dates dépendantes) et les communications : 22 octobre, conditionnel.",
         owner="Nicolas Perron", owner_status="proposé (chargé de projet, F24; note de transition)",
         evidence="Note_transition_Elodie_16sept.txt ; Teams 15 sept ; Plan_Projet_NOVA_v3 D7:G7", due="à confirmer (avant diffusion)",
         condition="Hors conditions; nécessaire à la cohérence", theme="Échéancier"),
    dict(id="A05", priority=2, action="Retenir la ligne CR-04 (18 000 $) sur INV-003 et demander à Boréal une facture corrigée ou un avoir; traiter le reste (36 000 $ jalon 3) après validation du jalon.",
         owner="Nicolas Perron (décision); Amélie Fortin (Finances, traitement)", owner_status="proposé (E07, E10; question en attente)",
         evidence="INV-003.pdf (page 1, ligne CR-04); E07; E10; Decision_Portee_Phase2.md", due="à confirmer (avant libération de INV-003)",
         condition="Hors conditions; budget", theme="Factures"),
    dict(id="A06", priority=2, action="Corriger le rapport de statut : sécurité et accessibilité non VERT tant que SEC-210 et ACC-303 ne sont pas acceptés; ne pas diffuser le brouillon « NOVA est au vert ».",
         owner="Nicolas Perron (proposé; propriétaire du rapport non identifié dans le corpus)", owner_status="proposé",
         evidence="Rapport_Statut_21sept.pdf (page 1); E11; E09", due="à confirmer",
         condition="Hors conditions; communication", theme="Échéancier"),
    dict(id="A07", priority=2, action="Mettre à jour le registre des risques : R-01 (fermer ou actualiser après le 17 septembre), R-02 à R-04 maintenus ouverts.",
         owner="Nicolas Perron (proposé); Marc Gervais pour R-01", owner_status="proposé (propriétaires de risques, F40)",
         evidence="Registre_Risques_29sept.xlsx (F2:H5)", due="à confirmer",
         condition="Hors conditions; gouvernance", theme="Risques"),
    dict(id="A08", priority=3, action="Produire la validation technique de la migration Canada Central exigée par ADR-007 avant les tests de production.",
         owner="Marc Gervais (architecture)", owner_status="proposé (ADR-007; M03 vérification architecture)",
         evidence="ADR-007 (Conséquences); M03; E03", due="à confirmer (avant tests de production)",
         condition="Hors conditions; prérequis technique", theme="Architecture"),
    dict(id="A09", priority=3, action="Obtenir le compte rendu signé du comité du 10 septembre et celui du 26 septembre (absents du corpus).",
         owner="Nicolas Perron", owner_status="proposé (Nicolas annonce « Je publie le compte rendu »)",
         evidence="M06 10:30; absence dans le corpus", due="à confirmer",
         condition="Hors conditions; traçabilité", theme="Gouvernance"),
    dict(id="A10", priority=3, action="Confirmer que la réouverture du mobile (CR-04) reste hors phase 1 et qu'aucune dépense n'est engagée.",
         owner="Nicolas Perron", owner_status="confirmé (décision de portée F34)",
         evidence="Decision_Portee_Phase2.md; E10; M04 15:37", due="en vigueur",
         condition="Hors conditions; budget", theme="Budget"),
]

CONDITIONS = [
    dict(n=1, text="Validation sécurité de SEC-210", actions=["A01"], status="ouvert: livré, non accepté"),
    dict(n=2, text="Fermeture de ACC-303", actions=["A02"], status="ouvert"),
    dict(n=3, text="Approbation du runbook incluant le rollback", actions=["A03"], status="ouvert: étapes 4 et 5 incomplètes"),
]
